### ISSUE TITLE
Change featured Q8_0 files to Q6_K for Metal support

### ISSUE THREAD

**Issue by yagil** [lmstudio-ai/model-catalog#18]
Some models feature Q8_0 files, but that quant isn't supported in Metal. 
This issue is for replacing those quant with Q6_K versions s.t. the model will work with Metal ON.

**Comment by felladrin** [comment]
Let me update them. But I noticed https://huggingface.co/TheBloke/MPT-7B-Storywriter-GGML/tree/main and https://huggingface.co/TheBloke/WizardCoder-15B-1.0-GGML/tree/main don't have the new quantised files (_K). Do you think it's worth pointing their 'most capable' to the `q5_1` file?

**Comment by yagil** [comment]
Thanks @felladrin! 🦾
It's a good question re MPT and WizardCoder. I don't have data on the performance delta (qualitative / quantitive) between q5_1 and q8_0. Hypothetically q8_0 should be better and therefore correctly labeled. LMS doesn't have Metal support for non-Llama yet, so it's going to be fully CPU either way.

**Comment by felladrin** [comment]
Ok, PR created. I suggest using q5_1 as the "most capable" (even if q8_0 is better) due to the smaller size and because TheBloke usually mentions that q8_0 is "not recommended for normal use".
<img width="730" alt="image" src="https://github.com/lmstudio-ai/model-catalog/assets/418083/20a5e776-f7f3-4b5d-93ed-89c7d9442592">
